import { AppIcon, FileSystemNode, ProgramType } from '../types'

// Current last id: 14
export const FILE_SYSTEM: FileSystemNode[] = [
  {
    id: 0,
    fileName: 'root',
    title: 'Explorer',
    type: ProgramType.Folder,
    iconKey: AppIcon.FolderColored,
    contentKey: '0',
    children: [
      {
        id: 1,
        fileName: 'console',
        title: 'Cmd line',
        type: ProgramType.App,
        iconKey: AppIcon.Code,
        contentKey: 'Cmd line',
      },
      {
        id: 2,
        fileName: 'settings',
        title: 'Settings',
        type: ProgramType.App,
        iconKey: AppIcon.Settings,
        contentKey: 'Settings',
      },
      {
        id: 3,
        fileName: 'portfolio',
        title: 'Portfolio',
        type: ProgramType.App,
        iconKey: AppIcon.Folder,
        contentKey: 'Portfolio',
      },
      {
        id: 4,
        fileName: 'cv',
        title: 'Cv',
        type: ProgramType.Folder,
        iconKey: AppIcon.Folder,
        contentKey: '4',
        children: [
          {
            id: 7,
            fileName: 'about-me',
            title: 'About me',
            type: ProgramType.App,
            iconKey: AppIcon.Folder,
            contentKey: 'About me',
          },
          {
            id: 8,
            fileName: 'skills',
            title: 'Skills',
            type: ProgramType.App,
            iconKey: AppIcon.Folder,
            contentKey: 'Skills',
          },
          {
            id: 9,
            fileName: 'education',
            title: 'Education',
            type: ProgramType.App,
            iconKey: AppIcon.Folder,
            contentKey: 'Education',
          },
          {
            id: 10,
            fileName: 'experience',
            title: 'Experience',
            type: ProgramType.App,
            iconKey: AppIcon.Folder,
            contentKey: 'Experience',
          },
        ],
      },
      {
        id: 5,
        fileName: 'apps',
        title: 'Apps',
        type: ProgramType.Folder,
        iconKey: AppIcon.Folder,
        contentKey: '5',
        children: [
          {
            id: 13,
            fileName: 'calculator',
            title: 'Calculator',
            type: ProgramType.App,
            iconKey: AppIcon.Calculator,
            contentKey: 'Calculator',
          },
          {
            id: 14,
            fileName: 'random-advice',
            title: 'Random advice',
            type: ProgramType.App,
            iconKey: AppIcon.QuoteMark,
            contentKey: 'Random advice',
          },
        ],
      },
      {
        id: 6,
        fileName: 'links',
        title: 'Links',
        type: ProgramType.Folder,
        iconKey: AppIcon.Folder,
        contentKey: '6',
        children: [
          {
            id: 11,
            fileName: 'GitHub',
            title: 'GitHub',
            type: ProgramType.Link,
            iconKey: AppIcon.GitHub,
            contentKey: 'https://github.com/jaakkomaenpaa',
          },
          {
            id: 12,
            fileName: 'LinkedIn',
            title: 'LinkedIn',
            type: ProgramType.Link,
            iconKey: AppIcon.LinkedIn,
            contentKey: 'https://www.linkedin.com/in/jaakko-mäenpää-37a11a262',
          },
        ],
      },
    ],
  },
]
